"""Shared visualization style for GraphGuard figures."""
from .style import (
    PALETTE,
    PINK,
    PINK_DARK,
    BLUE,
    BLUE_DARK,
    GREEN,
    LAVENDER,
    PEACH,
    GRAY,
    BLACK,
    WHITE,
    LINESTYLES,
    MARKERS,
    apply_rc,
    save_fig,
    despine,
    color_for_verdict,
    annotate_bars,
)
